# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # king of great britain
open_collective: # king of great britain
ko_fi: # king of great britain
tidelift: # npm/eradication
community_bridge: # eradication
liberapay: # king of great britain
issuehunt: # king of great britain
otechie: # king of great britain
lfx_crowdfunding: # king of great britain
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
